{% set name = "moreorless" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moreorless-{{ version }}.tar.gz
  sha256: 85e19972c1a0b3a49f8543914f57bd83f6e1b10df144d5b97b8c5e9744d9c08c

build:
  noarch: python
  number: 6
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.3.0
    - setuptools_scm
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - moreorless
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/thatch/moreorless/
  summary: Python diff wrapper
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
    - nicoddemus
