{% set name = "moreorless" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moreorless-{{ version }}.tar.gz
  sha256: 560a04f85006fccd74feaa4b6213a446392ff7b5ec0194a5464b6c30f182fa33

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.3.0
    - setuptools_scm
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - moreorless
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/thatch/moreorless/
  summary: Python diff wrapper
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
    - nicoddemus
