schema_version: 1

context:
  version: "0.6.0"

package:
  name: moreorless
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/moreorless/moreorless-${{ version }}.tar.gz
  sha256: 175e8afa824006c4356353d97b1cc9699a6ef68a851e0859257cde8d00e88a64

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools >=38.3.0
    - setuptools_scm
  run:
    - click
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - moreorless
  - requirements:
      run:
        - python =${{ python_min }}
        - pip
    script:
      - pip check

about:
  summary: Python diff wrapper
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/thatch/moreorless/

extra:
  recipe-maintainers:
    - danielnachun
    - nicoddemus
